MiMailIdentity/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MiMailIdentity.Models
{
    public class Customer : BaseModel
    {
        public int CustomerCateId { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public string CMT { get; set; }
        public int Gender { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        

        [ForeignKey("CustomerCateId")]
        public virtual CustomerCategory GetCategory { get; set; }
    }
}

MiMailIdentity/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language.Extensions;
using MiMailIdentity.Data;
using MiMailIdentity.Helper.AccountHelper;
using MiMailIdentity.Models;
using MiMailIdentity.Services.BaseRepository;
using MiMailIdentity.Services.CustomerRepository;

namespace MiMailIdentity.Controllers
{
    public interface Icustomer : IBaseRepository<Customer>
    {

    }
    public class Customerss : BaseRepository<Customer>
    {
        public Customerss(ApplicationDbContext identityContext, ModelDbContext context, IAccountHelper account) : base(identityContext, context, account)
        {

        }
    }
    public class CustomersController : Controller
    {
        private ICustomerRepository _repo;
        public CustomersController(ICustomerRepository repository)
        {
            _repo = repository;
        }
        #region  Nghiep vu
        public IActionResult Index(int cateId, int? pageIndex, int? pageSize)
        {
            var index = pageIndex ?? 1;
            var size = pageSize ?? 10;
            ViewBag.CateId = cateId;
            ViewBag.index = index;
            ViewBag.size = size;
            return View();
           
        }
        //[HttpPost]
        //public IActionResult Load((FilterCustomer filter)
        //{
        //    return ViewComponent("ListCustomer", new { CateId = cateId, PageIndex = pageIndex, PageSize = pageSize });
        //}
        [HttpPost]
        public IActionResult Save(Customer cus)
        {
            if(cus != null)
            {
                if(cus.Id > 0)
                {
                    //update
                    _repo.Update(cus);
                    return Ok(new { Status = true, mess = "Update Successful" });
                    
                }
                else if(cus.Id <= 0)
                {
                    //insert
                    _repo.Insert(cus);
                    return Ok(new {Status = true,mess = "Save Successful" });
                }
            }
            return BadRequest(new { Status = false, mess = "save erro" });
        }
        [HttpPost]
        public IActionResult Filter(FilterCustomer filter)
        {
            
            return ViewComponent("ListCustomer", new { filter = filter });
        }
        #endregion

        #region Giao Dien
        [HttpPost]
        public IActionResult AddModal(int Id)
        {
            return ViewComponent("ModalSave", new { Id = Id });
        }
        public IActionResult OpenModalChiTiet(int Id)
        {
            return ViewComponent("ModalKhachHangChiTiet", new { Id = Id });
        }
        #endregion
    }
}

MiMailIdentity/ViewComponents/Customer/ListCustomerFilterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiMailIdentity.Services.CustomerRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiMailIdentity.ViewComponents.Customer
{
    public class ListCustomerFilterViewComponent : ViewComponent
    {
        private ICustomerRepository _repo;
        public ListCustomerFilterViewComponent(ICustomerRepository repo)
        {
            _repo = repo;
        }
        public IViewComponentResult Invoke(FilterCustomer filter)
        {
            
            return View();
        }
    }
}

MiMailIdentity/ViewComponents/Customer/ListCustomerViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MiMailIdentity.Services.CustomerRepository;
using Microsoft.AspNetCore.Mvc;

namespace MiMailIdentity.ViewComponents.Customer
{
    public class ListCustomerViewComponent : ViewComponent
    {
        private ICustomerRepository _repo;
        public ListCustomerViewComponent(ICustomerRepository customers)
        {
            _repo = customers;
        }
        public IViewComponentResult Invoke(FilterCustomer filter)
        {
           
            return View(filter);
        }
    }
}

MiMailIdentity/ViewComponents/Customer/ModalKhachHangChiTietViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiMailIdentity.Services.CustomerRepository;

namespace MiMailIdentity.ViewComponents.Customer
{
    public class ModalKhachHangChiTietViewComponent : ViewComponent
    {
        private ICustomerRepository _repon;
        public ModalKhachHangChiTietViewComponent(ICustomerRepository repon)
        {
            _repon = repon;
        }
        public IViewComponentResult Invoke(int Id)
        {
            var result = _repon.GetById(Id);
            return View(result);
        }
    }
}

MiMailIdentity/ViewComponents/Customer/ModalSaveViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiMailIdentity.Models;
using MiMailIdentity.Services.CustomerRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiMailIdentity.ViewComponents.Customer
{
    
    public class ModalSaveViewComponent : ViewComponent
    {
        private ICustomerRepository _repon;
        public ModalSaveViewComponent(ICustomerRepository repon)
        {
            _repon = repon;
        }
        public IViewComponentResult Invoke(int Id)
        {
            ViewBag.Id = Id;
            return View();
        }
    }
}

MiMailIdentity/Views/Customers/Index.cshtml
@using MiMailIdentity.Services.CustomerCategoryRepository
@using MiMailIdentity.Services.CustomerRepository
@model List<Customer>
@inject ICustomerCategoryRepository _repons;
@using MiMailIdentity.Helper.AccountHelper;
@inject IAccountHelper _accountHelper
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutPublic.cshtml";
    var cateId = ViewBag.CateId;
    int pageindex = ViewBag.index;
    int pagesize = ViewBag.size;
    var ListCates = _repons.GetAll().ToList();

}

<section>
    <div class="p-2 border-top">
        <div class="container">
            <div class="giaidoan d-flex">
                <div class="turn-chimuc d-flex">
                    <div class="nb-turn mr-1 ">1</div>
                    <div>Nhóm khách hàng</div>
                </div>
                <div class="line-turn"></div>
                <a href="/danh-sach-kh/nhom/1" class="turn-chimuc d-flex  active">
                    <div class="nb-turn mr-1">2</div>
                    <div>List danh sách kH</div>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="process-list-khang">
    <div class="container">
        <div class="row">
            <div class="col-1">
                <div class="">
                    <div id="process-bar" class="process-group"></div>
                </div>
            </div>
            <div class="col-11">
                @{ 
                    var IdAcc = _accountHelper.GetCurrentUserAsync().Id;
                    var AccCount = _accountHelper.GetById(IdAcc);
                }
                <span class="tke-turn">Tài khoản dùng thử miễn phí của bạn có giới hạn <span class="all-turn-co">@AccCount.MaxMail</span> liên hệ. Bạn có thể thêm <span class="turn-con">998</span> liên hệ</span>
                <div class="tke-turn-sudung"> <span class="turn-daco">2</span> / @AccCount.MaxMail Liên hệ</div>
            </div>
        </div>
    </div>
</section>
<section class="main-data-custmer pt-0">
    <div class="container">
        <div class="bg-fff">
            <div class="tracuu-khhang">
                <div class="row">
                    <div class="col-md-4">
                        <div class="cus-name">
                            <label for="name-input" class="cus-ic-box">
                                <i class="fal fa-search"></i>
                            </label>
                            <input type="text" name="txtName" id="FintName" placeholder="Nhập tên , sđt, email..." class="w-100 ip-css">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="cus-name">
                            <select class="form-control" id="FintCate">
                                <option value="0">Chọn tất cả</option>
                                @foreach (var item in ListCates)
                                {
                                    if (cateId == item.Id)
                                    {
                                        <option value="@item.Id" selected>@item.Name</option>
                                    }
                                    <option value="@item.Id">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="cus-name">
                            <label for="name-input" class="cus-ic-box">
                                <i class="fal fa-search"></i>
                            </label>
                            <input type="text" id="searchTime" placeholder="Thời gian nhập" class="w-100 ip-css" autocomplete="off" value="">
                        </div>
                    </div>
                    <div class="col-md-2 pt-3">
                        <button type="button" class="btn btn-success" id="search">Tìm</button>
                    </div>
                </div>
                <div class="d-flex align-items-center">
                    <div class="add-group">
                        <button type="button" class="btn btn-addgr" id="CreateKhachHang"><i class="fal fa-plus mr-2"></i> Tạo mới</button>
                        <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="myModalLabel">Tạo mới nhóm khách hàng</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <span>Nhóm khách hàng</span>
                                        <div style="padding-bottom: 33px;">
                                            <input type="text" placeholder="Nhập tên nhóm" style="font-size: 15px;padding: 0 10px;outline:none;" class="form-modal border">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
                                        <!-- <button type="button" class="btn btn-default btn-prev">Prev</button> -->
                                        <button type="button" class="btn btn-cancel" data-dismiss="modal">Cancel</button>
                                        <button type="button" class="btn btn-addgr btn-next">Add</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal2">Player 2</button> -->
                        <form id="Modal_Customer">
                            <div class="modal fade bd-example-modal-lg" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">


                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                    <a href="#">
                        <img src="~/img/export.png" alt="" class="ml-2">
                    </a>
                    <a href="#">
                        <img src="~/img/import.png" alt="" class="ml-2">
                    </a>
                </div>
            </div>

            <div class="content">
                <div class="table-responsive">
                    <table id="datatable" class="table cust-table">
                        @{
                            var filter = new FilterCustomer();
                            filter.StartDate = null;
                            filter.EndDate = null;
                            filter.CateId = cateId;
                            filter.Name = "";
                            filter.pageIndex = pageindex;
                            filter.pageSize = pagesize;
                        }
                        @await Component.InvokeAsync("ListCustomer", new { filter = filter })
                    </table>
                </div>
            </div>

        </div>
        <div id="pagination">

        </div>
    </div>



</section>
<div class="modal fade bd-example-modal-lg info-kh" id="ModalChiTiet" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>

@section scripts{
    <script>
        var dpk = $('#searchTime');
        R.DatePicker(dpk, false);
    </script>
    <script>
        var percentage = 40;
        var bar = new ProgressBar.Circle('#process-bar', {
            strokeWidth: 10,
            color: '#000000',
            trailColor: '#eee',
            trailWidth: 1,
            easing: 'easeInOut',
            duration: 1400,
            svgStyle: null,
            text: {
                value: '',
                alignToBottom: false
            },
            from: {
                color: '#F26D21'
            },
            to: {
                color: '#F26D21'
            },
            // Set default step function for all animate calls
            step: (state, bar) => {
                bar.path.setAttribute('stroke', state.color);
                var value = percentage;
                if (value === 0) {
                    bar.setText('');
                } else {
                    bar.setText(value + "/200 Liên hệ");
                }

                bar.text.style.color = state.color;
            }
        });

        bar.text.style.fontFamily = '"Raleway", Helvetica, sans-serif';
        bar.text.style.fontSize = '36px';
        bar.animate(percentage / 200); // Number from 0.0 to 1.0
    </script>
    <script>
        $("div[id^='myModal']").each(function () {

            var currentModal = $(this);

            //click next
            currentModal.find('.btn-next').click(function () {
                currentModal.modal('hide');
                currentModal.closest("div[id^='myModal']").nextAll("div[id^='myModal']").first().modal('show');
            });

            //click prev
            currentModal.find('.btn-prev').click(function () {
                currentModal.modal('hide');
                currentModal.closest("div[id^='myModal']").prevAll("div[id^='myModal']").first().modal('show');
            });

        });
    </script>
    <script src="~/controllerJs/CustomersController.js"></script>
}